#pragma once

#define MAX_LOOP_STEPS 32
#define MAX_PATTERN_STEPS MAX_LOOP_STEPS

#define VEL_ACCENTED 100
#define VEL_NORMAL 60
#define VEL_MIDDLE ((VEL_ACCENTED+VEL_NORMAL)/2)
#define MIDI_VAL_ON 127
#define MIDI_VAL_OFF 0
#define CC_PORTAMENTO 65
#define DRUM_ACCENTED 127
#define DRUM_NORMAL 90
#define DRUM_MIDDLE ((DRUM_ACCENTED+DRUM_NORMAL)/2)

#define NOTE_LENGTH_303 6
#define SLIDE_LENGTH_303 20
#define NOTE_STACK_SIZE 3